### PR TITLE
Switch to GitHub Actions to generate website

### PR DESCRIPTION
**Pull request by gabrielcossette**
Preliminary work for PR #1531. This PR switches Jekyll website generation to GitHub Actions (as per [Jekyll instructions](https://jekyllrb.com/docs/continuous-integration/github-actions/)). The website will now be published to the `gh-pages` branch (using a token variable I generated from my account).

This will give us more flexibility overall. For example, to import Bootstrap sources without including it in our repo (thanks @smellems for the suggestion!).

After it is merged, I will switch our repository "publishing sources" to the new `gh-pages` branch.

### CODE REVIEW

**Comment by gcharest** [comment]
Tests are failing: https://drop.infini.fr is not responding (no server error, just times out)

Rest seems fine with me. @smellems ?

**Comment by gabrielcossette** [comment]
Sorry, filename for the actual GitHub Actions YML was wrong. Fixed now.

**Review by smellems — CHANGES_REQUESTED** [review]
I like adding a Gemfile, but

wait to confirm if we need move to Github action.
https://github.com/sara-sabr/ITStrategy/pull/1531#discussion_r574023286

**Review by smellems — APPROVED** [review]
Github actions is needed since Github pages gives error with SCSS and bootstrap gem.

> Your site is having problems building: Your SCSS file assets/css/style.scss has an error on line 2: File to import not found or unreadable: bootstrap. Load paths: assets/css /hoosegow/.bundle/ruby/2.7.0/gems/jekyll-theme-primer-0.5.4/_sass.

**Pull request merged**
