### PR TITLE
Micro-Acquisition branding and content

### PR DESCRIPTION
**Pull request by RachelMuston**
Added a new Micro-Acquisition page using the one pager text
Removed the old Micro-procurement page (archived the content in a word file on the Sharepoint site)

### CODE REVIEW

**Review by gcharest — CHANGES_REQUESTED** [review]
I'm OK with the rebranding but we probably should include a redirect if we're changing the pages URL?

Will double check if we did that in the past. If not I've done it on my site (gcharest.ca)

**Comment by RachelMuston** [comment]
Oh geez, good point @gcharest!  We definitely should have a redirect on the old micro-procurement page.

**Comment by RachelMuston** [comment]
we don't have a page-redirect.md file in the includes folder on our site so I'm assuming we haven't done before. I'll create a separate PR to add the includes file. :)

**Comment by gcharest** [comment]
I'm using the jekyll-page-redirect plugin on my site. Might be useful here but will need to test out

**Comment by gcharest** [comment]
Plugin: https://github.com/jekyll/jekyll-redirect-from

**Comment by RachelMuston** [comment]
Ah interesting....shifting comments on this over to the new PR for the redirect.... #1405

**Review by gcharest — APPROVED** [review]
Approved with latest changes!

**Review by gabrielcossette — APPROVED** [review]
Great work! It's good to go :)

**Pull request merged**
