### PR TITLE
Build vs Buy Strategy

### PR DESCRIPTION
**Pull request by jaysonmc**
#350

### CODE REVIEW

**Comment by gcharest** [comment]
Why are there changes to _pages/en/iitb-kpi.md and wip-tec/en/GcDevopsImplementation.md?

**Comment by jaysonmc** [comment]
Dead links were causing build to fail. Should be in the commit logs

**Comment by smellems** [comment]
The link still works, do we want to keep it?

**Comment by smellems** [comment]
We need to add something about Total Cost of Ownership (TCO).  The decision to buy or build, or use OSS and build missing features, depends on the TCO.  See guidance for [Using OSS](https://github.com/canada-ca/open-source-logiciel-libre/blob/master/en/guides/using-open-source-software.md#actively-and-fairly-consider-open-source-software), approved at EARB and to be published on canada.ca

1. SaaS based on Free OSS (FOSS) using open standards
1. SaaS based on FOSS
1. SaaS based on Commercial OSS (COSS) using open standards
1. SaaS based on COSS
1. SaaS based on COTS using open standards
1. SaaS based on COTS
1. FOSS using open standards deployed on XaaS
1. FOSS using open standards deployed on premise
1. FOSS deployed on XaaS
1. FOSS deployed on premise
1. COSS using open standards deployed on XaaS
1. COSS using open standards deployed on premise
1. COSS deployed on XaaS
1. COSS deployed on premise
1. COTS using open standards deployed on XaaS
1. COTS using open standards deployed on premise
1. COTS deployed on XaaS
1. COTS deployed on premise
1. Custom build - Using FOSS and open standards deployed on XaaS
1. Custom build - Using FOSS and open standards deployed on premise
1. Custom build - Using FOSS deployed on XaaS
1. Custom build - Using FOSS deployed on premise
1. Custom build - Using COSS and open standards deployed on XaaS
1. Custom build - Using COSS and open standards deployed on premise
1. Custom build - Using COSS deployed on XaaS
1. Custom build - Using COSS deployed on premise
1. Custom build - ...

I did'nt really want to split OSS into FOSS and COSS but it happened, COSS is basically open core (OSS with closed source components)

For FOSS, COSS and COTS, the full lifecycle TCO needs to be a consideration, including "building" missing functionality for a solution

**Comment by smellems** [comment]
1. **(Adopt) SaaS based on**
  1.1 OSS using open standards
  1.2 OSS
  1.3 OSS + COTS using open standards
  1.4 OSS + COTS - (be aware of lock-in)
  1.5 COTS using open standards - (be aware of lock-in)
  1.6 COTS - (be aware of lock-in)
1. **(Buy/Adopt) Solutions deployed on XaaS or on premise**
  1.1 OSS using open standards
  1.2 OSS
  1.3 OSS + COTS using open standards
  1.4 OSS + COTS - (be aware of lock-in)
  1.5 COTS using open standards - (be aware of lock-in)
  1.6 COTS - (be aware of lock-in)
1. **(Build/Adopt) Custom solutions**
  1.1 Using OSS and open standards
  1.2 Using OSS
  1.3 Using OSS + COTS using open standards
  1.4 Using OSS + COTS
  1.5 Using COTS and open standards
  1.6 Using COTS - (be aware of lock-in)
  1.7 From scratch (tech stack must be OSS and use open standards..)

**Pull request merged**
