### PR TITLE
Ui changes

### PR DESCRIPTION
**Pull request by gcharest**
- Updated the Splash screen to be more alive (changed Jumbotron to custom display)
- Lightened up the overall theme (more white and contrast)
- Added dynamic drop-down menus to the following sections:
  - About us
  - Ready for use documents (aka Our strategies)
- Renamed Working in the Open page as it was way too long.

A few things to work out in upcoming PRs:
- Navigation structure (should be a different PR altogether, requires better information architecture discussion)
- Trigger the collapse of the menu at higher resolution (currently at mobile) so that ipad display looks good as well

### CODE REVIEW

**Comment by gcharest** [comment]
Fixes #467

**Comment by smellems** [comment]
I like that this doesn't add too many new Javascript and CSS files and is more improving what we have with bootstrap. 😄

**Comment by gabrielcossette** [comment]
I reduced the margins of the header section (as it was before). Let me know if you prefer to keep larger one.

**Comment by gabrielcossette** [comment]
If we are on a page without a FR translation, the "Our Strategies" sub-menu is too large (see image):
image

**Comment by gabrielcossette** [comment]
2 suggestions:
1. Display the SABR logo top left instead of "IT STRATEGY" (duplicate from header section)?
2. Add change of color when hovering items in menu?

**Comment by gabrielcossette** [comment]
Forgot to mention above that if you agree with my suggestions, I can help with the work!

**Comment by gcharest** [comment]
@smellems Good catch on the image, will double check if actually in used and if so, will need to compress.

> 2 suggestions:
> 
>     1. Display the SABR logo top left instead of "IT STRATEGY" (duplicate from header section)?
> 
>     2. Add change of color when hovering items in menu?

@gabrielcossette I like the logo idea! Regarding hover in menu: 100%

**Comment by gcharest** [comment]
> If we are on a page without a FR translation, the "Our Strategies" sub-menu is too large (see image):
> image

You mean the white space at the right?

**Comment by gabrielcossette** [comment]
> 
> 
> > If we are on a page without a FR translation, the "Our Strategies" sub-menu is too large (see image):
> > image
> 
> You mean the white space at the right?

I mean, the title is cut out. We can't see the full title of this particular Strategy.

**Comment by gcharest** [comment]
> > > If we are on a page without a FR translation, the "Our Strategies" sub-menu is too large (see image):
> > > image
> > 
> > 
> > You mean the white space at the right?
> 
> I mean, the title is cut out. We can't see the full title of this particular Strategy.

Hmmm... Need to better think those links then. Either the page title is too long itself or we need it wrapped?

**Comment by gcharest** [comment]
@gabrielcossette Should we merge now or address the dropdown points first?

**Pull request merged**
