### PR TITLE
Software onboarding wireframe demo

### PR DESCRIPTION
**Pull request by jaysonmc**
Initial wireframe for software onboarding demo

### CODE REVIEW

**Comment by smellems** [comment]
I think we should mention NPM packages, since Node is already approved and they are like plugins.

- CLI Software to onboard
  - NPM
    - Enter name and version of package from npmjs.com
      - Security (npm audit)
      - OSS licence (OSI or FSF)
  - Other

We could also automate checks for Ruby and Python packages if those languages are approved

**Comment by jaysonmc** [comment]
@smellems 
Okay, I specified that it's only npm for now. Can add others as we go

**Comment by smellems** [comment]
For production or experimentation..  I think we should ask if the package will be used
- as part of a production application or to build the production application;
- for testing and experimentation (including testing of production applications)

Also, since this is about OSS do we want to ask if they will be modifying the code or assume that they wont?

**Comment by gcharest** [comment]
So, this is pretty good and I was wondering about the reference to NPM only. What about everything else? 

Also, that's for the "initial" onboarding. Do we look into the tracking and maintaining of these dependencies?

**Comment by gcharest** [comment]
And it's developer intended, correct?

**Pull request merged**
