### PR TITLE
ABB-explained FR 

### PR DESCRIPTION
**Pull request by ElminaIusifova**

### CODE REVIEW

**Comment by RachelMuston** [comment]
This is passing checks and the code matches the English version of the file. The text itself needs a quality check (on the translation)

**Review by gabrielcossette — APPROVED** [review]
It was short so I reviewed it. Good to go!

**Review by gcharest — APPROVED** [review]
Updated links and fix warnings (scope creep but not breaking changes.)

**Comment by gcharest** [comment]
Great work @ElminaIusifova ! :clap:

**Pull request merged**
