### PR TITLE
Updates to next steps and speaking notes (micro-procurement deck for DG Comm)

### PR DESCRIPTION
**Pull request by RachelMuston**
(mostly). A few other minor changes too.

### CODE REVIEW

**Comment by ElminaIusifova** [comment]
Suggestion: how about adding a slide that will show what steps will take us to develop a light project?

**Comment by RachelMuston** [comment]
Can you share a bit more @ElminaIusifova? I did update the Next Steps slide to include the approval steps in the lite project process (e.g. EA review, BPMO endorsement).  Perhaps you are thinking of listing the documents we'll be creating as part of the process?

**Comment by ElminaIusifova** [comment]
@RachelMuston here I mean a product development phase itself, starting from design and ending with accessibility and security check. Just to show the steps of product development and how long approximately every step will take us to develop the whole "light project". Ex: (roughly) we start from user research ->develop a wireframe ->test it on a user ->iterate ->develop a prototype .......  That next step is: come back and iterate the platform after 1 year of user feedback. Can a slide like this be useful? Sorry if I couldn't explain it well

**Comment by RachelMuston** [comment]
Ahhh I understand now! You explained it perfectly. :)  We'll definitely have that detail in the schedule we'll be creating as part of our project approval. Just wondering at what level of detail we should be including that in the DG Comm deck. 
There's probably only room for about one or two additional bullets on this slide.  I'm open to suggestions.  Some options:
Option 1: 
- EA review
- BPMO endorsement
- Exec sponsor endorsement
- PPOC endorsement
- product design
- product launch
(in the speaking notes I would describe the product design process)

Option 2:
-Approvals via lite project process
- project launch
--product design
-- product development
-- pilot launch

I guess it depends on what DG Comm cares most about/what we want them to know?

**Comment by ElminaIusifova** [comment]
I assume we don't need to go too detailed, maybe just a high-level explanation to give a general idea of the product development and what IT Strategy will be going through if we fully develop the light project. Would DG Comm even care about this?

**Comment by RachelMuston** [comment]
That's the thing...I'm not sure what DG Comm cares about. I have a feeling they care mostly about things like approvals, security etc. They should care about UX and product design though. I'm leaning towards keeping that detail in speaking notes rather than on slides.  Is it ok if we see what Phil thinks?

**Review by ElminaIusifova — APPROVED** [review]

**Review by smellems — APPROVED** [review]

**Pull request merged**
