### PR TITLE
Reduce width of webpages (excl. tables) + Adjust font sizes

### PR DESCRIPTION
**Pull request by gabrielcossette**
Hi,

Here's an attempt to reduce the width of our webpages to make them more readable. They should now look similar to articles on [Medium.com](https://medium.com) for example.

One exception is the tables. I've found that making them more narrow would hurt readability, so I left them wide (but they'll auto resize according to their content).

Finally, I've also adjusted the font sizes to make them more readable (headers, text...)

I'm not an UI/UX specialist so let me know if we need to tweak these changes. Also, I'm sure there are more elegant ways to code this so I'm open to any suggestions :)

### CODE REVIEW

**Review by RachelMuston — COMMENTED** [review]
I've added @ElminaIusifova as a reviewer as I think this needs her eyes for sure. 

I'm glad we are doing this. Thanks @gabrielcossette.  I feel that in implementing this we might need some additional CSS changes.  When I look at Medium, things like author name and date are in a smaller font than the body text and I think that makes the top part of a page a lot more readable.  Here's an example...https://honeygolightly.medium.com/enabling-conditions-not-just-heroics-110a2faba643. 

Also we should check what this change looks like on all our pages (not just our blog pages)...A quick glance at our 'Mandate' page makes me think that there should be more of a size difference between the h1 title and the h2 headers (at least I am assuming they are h1 and h2). The sizing of this text is not new but somehow with more white space on either side it makes those h2 headers look too big. My non UX-expert $0.02. :)

**Comment by gcharest** [comment]
Agreed with @RachelMuston The change has an impact on the overall site look and feel (jumbotron and footer sections for example seem a little bit out of place in the new layout)

I think we're due for an overall cleanup and this might be occasion to start highlight the changes.

Width of blog posts makes sense but for rest of the content we'd probably need some adjustments before merging?

**Comment by gabrielcossette** [comment]
> When I look at Medium, things like author name and date are in a smaller font than the body text and I think that makes the top part of a page a lot more readable. Here's an example...https://honeygolightly.medium.com/enabling-conditions-not-just-heroics-110a2faba643.

Good point! I just made "author" (blog posts) and "version" (pages) top parts smaller :)

**Comment by gabrielcossette** [comment]
> Width of blog posts makes sense but for rest of the content we'd probably need some adjustments before merging?

Agreed. I'll make quickly another PR just for the blog posts and keep this one for the whole site :)

**Comment by gabrielcossette** [comment]
> Good point! I just made "author" (blog posts) and "version" (pages) top parts smaller :)

As well as "Last modified" just now.

**Comment by gcharest** [comment]
Propose we close this PR and work on #1392 for now? @gabrielcossette  what do you think?

**Review by ElminaIusifova — CHANGES_REQUESTED** [review]
I have the same thoughts here as well.  I would leave the width the same but change the body text for 18px. 
Then, the H2 headline size is 38px, the H3 one is 25px.

**Comment by gabrielcossette** [comment]
> Propose we close this PR and work on #1392 for now? @gabrielcossette what do you think?

Let's focus on #1392 first but I think we can keep this one open for changes to apply to the whole site (e.g., new font size).

**Comment by gabrielcossette** [comment]
I updated the font sizes to the following (values are not exact because I'm using the scalable "rem" CSS unit):

&nbsp;&nbsp;&nbsp;H1 = 44,96px
&nbsp;&nbsp;&nbsp;H2 = 37,92px
&nbsp;&nbsp;&nbsp;H3 = 24,96px
&nbsp;&nbsp;&nbsp;H4 = 20px
&nbsp;&nbsp;&nbsp;Body = 17,92px
&nbsp;&nbsp;&nbsp;Date, Version… = 16px

**Comment by gcharest** [comment]
@gabrielcossette could you include the blockquote 1.25rem from #1400 issue? I believe this falls under this PR's scope

**Comment by gcharest** [comment]
Would #1531 cover the scope of this PR? If so we could close it if there's not going to be active development here?

**Comment by gabrielcossette** [comment]
> Would #1531 cover the scope of this PR? If so we could close it if there's not going to be active development here?

Not really. This current PR was rather a proposal to reduce the content width of all pages (not just blog posts).

If it hasn't been discussed, it would be good to bring this consideration to the Website redesign initiative. What do you think @ElminaIusifova?
I'm still for reducing page width to improve readability, but we should reach a consensus either way.

**Review by ElminaIusifova — APPROVED** [review]
@gabrielcossette the optimal line length for body text is considered to be 50-60 characters per line, including spaces. Maximum we can go up to 75.  Does this align with the changes you made?  If so, let's merge this PR.

**Comment by gabrielcossette** [comment]
> @gabrielcossette the optimal line length for body text is considered to be 50-60 characters per line, including spaces. Maximum we can go up to 75. Does this align with the changes you made? If so, let's merge this PR.

I adjusted the layout to about 75 characters per line, as general feedback from the team leaned toward larger width.

I'll consult the team again before merging, thanks!

**Pull request merged**
