### PR TITLE
Profile picture upload

### PR DESCRIPTION
**Pull request by RachelMuston**
added my profile picture to the assets folder.

### CODE REVIEW

**Comment by jaysonmc** [comment]
Im not closing so I can upload my picture to this PR too (when I get home). But also blocking the merge seems like overkill, so ...

**Comment by gabrielcossette** [comment]
I suggest we add all our profile pictures to this PR before merging. No rush to merge until we have a page ready to display them ;)

Suggested size for pictures? Square or rectangle format?

And someone's interested to create the profiles page?

**Comment by remyb2canada** [comment]
What specs must the picture have?
Width/height in pixels and image type (e.g. PNG)?

**Comment by RachelMuston** [comment]
Hi @remyb2canada! Square size for the pics pls. Current mock-up of the page has the images at 200px x 200px. But in case we want to go bigger best to make it at least 400px x 400px.  The css will define the size.  The way it is coded right now, consistent image type is not required.  We have a mix of png, and jpg.  That reminds me, @jaysonmc your pic is getting distorted in the rendering of the page.  Possible to get a new image for you?

**Comment by RachelMuston** [comment]
Also reminder to @Moro-Code - can you add your title and interests in english and french to members.yml?

**Comment by RachelMuston** [comment]
Also, was it wrong of me to add the draft team page files and the new data file to this branch/PR after the approval had started? Should the english and french team pages and data file be in a separate branch/PR?  If we merge this PR, the team page will be live.  Are we ok with how it looks?

**Pull request merged**
