### PR TITLE
Display blogs as cards

### PR DESCRIPTION
**Pull request by gcharest**
Changes default blog list into cards. Added recommended adaptations from [Heydon Pickering](https://inclusive-components.design/cards/) for accessible cards.

### CODE REVIEW

**Comment by gcharest** [comment]
New look when mouse hovering over a card:
image

**Comment by gcharest** [comment]
@gabrielcossette @ElminaIusifova @RachelMuston Would this be good to merge with the latest adjustments? Thanks!

**Comment by RachelMuston** [comment]
I like it! I'm still seeing the jumbotron...separate PR? or did we decide to leave in for now?

**Review by RachelMuston — APPROVED** [review]

**Comment by gcharest** [comment]
Yes, that's going to be a different PR to address the default layout 😊

**Pull request merged**
