### PR TITLE
Proposing an umberalla fund 

### PR DESCRIPTION
**Pull request by jaysonmc**
Inspired by a conversation with Arushi ... 

IT Strategy be responsible for a organizational Evolutionary IT Strategy fund

All projects run under this fund will run under our governance. Tool expenses and salaries will be run against the fund. We will grow the fund annually as we demonstrate success. 

Governance will start off largely non-existent and new ones will be created as need be as we scale up (more projects and responsibilities). 

Focus is on improving the organization by experimenting and sandboxing new approaches to benefit the organization. It differs from the innovation hub who is working on innovating new services. We are innovating governance within ESDC. 

Then all of our other points under mandates can be strictly enforced within our projects. Ex: Enforce use of JS on both client and server, cloud first, OSS only, etc...

### CODE REVIEW

**Comment by gcharest** [comment]
I support this suggestion

**Comment by remyb2canada** [comment]
This will require resources to do oversight and project management. Unless we can leverage IITB's PMO or PMRC?
I worry about the management burden

**Comment by gcharest** [comment]
There's many of us! (kidding, we do need to agree on T&Cs here)

**Comment by gabrielcossette** [comment]
Great proposal! Maybe we could merge on a single line? E.g.:
- Manage IT Strategic Evolution Fund, with full ownership and governance of projects

**Pull request merged**
