### PR TITLE
Add blog post navigation (previous, next)

### LINKED ISSUE #1465: Link blog posts series together
Simply make it easy for user to rotate through blog posts in a series.

Example: https://engineering.chrobinson.com/how-to/linking-a-series-of-jekyll-posts/

### PR DESCRIPTION
**Pull request by smellems**
Adds buttons to blogs, to navigate to previous and next blog post.

Example
image

Closes #1465

### CODE REVIEW

**Comment by gcharest** [comment]
Two things to consider:
- Navigation at the bottom only makes sense if we read the whole post but I'm wondering if it wouldn't be practical to have it at the top as well?
- The links should be equally spaced IMHO. Depending on the length of post titles, it makes it a bit inconsistent and sometimes the links run on top of each other. This [blog post explains](https://www.bytedude.com/jekyll-previous-and-next-posts/ */) how it's possible to use flexbox to better align the buttons on each side, even on mobile form.

**Review by gcharest — CHANGES_REQUESTED** [review]
Equally spread both links on each side of the page.
Consider adding the posts navigation links at the top as well

**Comment by gcharest** [comment]
Other reference in Bootsrap for navs and flex so that the buttons are equally spread: https://getbootstrap.com/docs/4.0/components/navs/#working-with-flex-utilities

**Comment by smellems** [comment]
Updated version uses Flexbox with a border

image

Small screen

image

**Review by ElminaIusifova — CHANGES_REQUESTED** [review]
If the purpose of this PR to navigate between blogs, the best way to add ARROWS (Arrow left -> "Previous", arrow right -> "Next"). I wouldn't put the name of the blogs on the button

**Comment by ElminaIusifova** [comment]
If you still want to leave the name of the blogs on the buttons I would remove the stroke on the box, make the font colour of the content  different, and increase the margin-top size

**Comment by gcharest** [comment]
There seems to be an odd behaviour when navigating around the posts :thinking: Like, some sort of loop?

**Comment by gcharest** [comment]
Nevermind the loop, propably a cache issue. Looks great!

Propose we add a visual indicator for hover/focus so that users who see can have a cue of the selectable area. Tab navigation works fine.

**Comment by gcharest** [comment]
> If the purpose of this PR to navigate between blogs, the best way to add ARROWS (Arrow left -> "Previous", arrow right -> "Next"). I wouldn't put the name of the blogs on the button

This change request has been actioned in [e031454](https://github.com/sara-sabr/ITStrategy/pull/1560/commits/e031454c1762ea68a042900b8eae64bee32ba320)

**Review by ElminaIusifova — CHANGES_REQUESTED** [review]
Can we remove the box around and add the word "blog"? :
<- Previous blog     -> Next blog

**Review by ElminaIusifova — APPROVED** [review]

**Pull request merged**
